### ISSUE TITLE
Cannot GET /api

### ISSUE THREAD

**Issue by arsalanhub** [jatin0002/Content_Management_System#2]
Connected to database & server running perfectly but when I visited http://localhost:5000/api above message is shown in the browser.

![Content_Management_System_error](https://user-images.githubusercontent.com/53657473/94676462-fcd80700-0338-11eb-80dc-6d69dd1831ee.png)

**Comment by jatin0002** [comment]
All the endpoint in this project

For signup(POST Request)
	api/signup 

For signin(POST Request)
	api/signin

For signout(GET Request)
	api/signout

For geting user details(you must be signin first and your token must be set)(GET Request)
	api/user/:userId

For updating user details(you must be signin first)(PUT Request)
	api/user/:userId

For creating article(you must be signin first and your Bearer token must be set)(POST Request)
	api/user/:userId/article/createarticle

For updating article(you must be signin first and your Bearer token must be set)(PUT Request)
	api/user/:userId/article/updatearticle/:articleId

For deleting article(you must be signin first and your Bearer token must be set)(PUT Request)
	api/user/:userId/article/removearticle/:articleId

For get all the article of particular user(you must be signin first and your Bearer token must be set)(GET Request)
	api/user/:userId/article/getallarticle
